trigger: none
pool: ps-pool

stages:
  - stage: terraform_installation
    displayName: terraform-display
    jobs:
      - job: terraform_installation_job1
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

  - stage: terraform_init
    displayName: terraform-init
    jobs:
      - job: terraform_init_job2
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/'
              backendServiceArm: 'pipeline-svc'
              backendAzureRmStorageAccountName: 'piplinestg1914'
              backendAzureRmContainerName: 'pipeline-container'
              backendAzureRmKey: 'pipeline.tfstate'

           
          

  
          