```yaml
trigger:
- main
- feature/*

pool: ps-pool

stages:

##########################################
# TERRAFORM INSTALLATION
##########################################

  - stage: terraform_installation
    displayName: terraform-display

    jobs:
      - job: terraform_installation_job1

        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'


##########################################
# TERRAFORM INIT
##########################################

  - stage: terraform_init
    displayName: terraform-init

    jobs:
      - job: terraform_init_job2

        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/'
              backendServiceArm: 'pipeline-svc'
              backendAzureRmStorageAccountName: 'piplinestg1914'
              backendAzureRmContainerName: 'pipeline-container'
              backendAzureRmKey: 'pipeline.tfstate'


##########################################
# TERRAFORM PLAN
##########################################

  - stage: terraform_plan
    displayName: terraform-plan

    dependsOn: terraform_init

    jobs:
      - job: terraform_plan_job3

        steps:

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/'
              backendServiceArm: 'pipeline-svc'
              backendAzureRmStorageAccountName: 'piplinestg1914'
              backendAzureRmContainerName: 'pipeline-container'
              backendAzureRmKey: 'pipeline.tfstate'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/'
              commandOptions: '-out=tfplan'
              environmentServiceNameAzureRM: 'pipeline-svc'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/tfplan'
              artifact: 'terraform-plan'
              publishLocation: 'pipeline'


##########################################
# TERRAFORM APPLY
##########################################

  - stage: terraform_apply
    displayName: terraform-apply

    dependsOn: terraform_plan

    # APPLY ONLY ON MAIN
    condition: and(
      succeeded(),
      eq(variables['Build.SourceBranch'], 'refs/heads/main')
    )

    jobs:
      - job: terraform_apply_job4

        steps:

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/'
              backendServiceArm: 'pipeline-svc'
              backendAzureRmStorageAccountName: 'piplinestg1914'
              backendAzureRmContainerName: 'pipeline-container'
              backendAzureRmKey: 'pipeline.tfstate'

          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: 'terraform-plan'
              targetPath: '$(System.DefaultWorkingDirectory)'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/'
              commandOptions: 'tfplan'
              environmentServiceNameAzureRM: 'pipeline-svc'
```
