trigger: 
- main
- feature/*

pool: ps-pool

stages:
  - stage: terraform_install
    displayName: terraform installation
    jobs:
      - job: terraform_job1
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
    
  - stage: terraform_init
    displayName: terraform init
    jobs:
      - job: terraform_job2
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/'
              backendServiceArm: 'rg-svc'
              backendAzureRmStorageAccountName: 'pipelinestg22092026'
              backendAzureRmContainerName: 'pipelinecontainer22092026'
              backendAzureRmKey: 'pipeline1.tfstate'

  - stage: terraform_plan
    displayName: terraform plan
    dependsOn: terraform_init
    jobs:
      - job: terraform_job3
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/'
              backendServiceArm: 'rg-svc'
              backendAzureRmStorageAccountName: 'pipelinestg22092026'
              backendAzureRmContainerName: 'pipelinecontainer22092026'
              backendAzureRmKey: 'pipeline1.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/'
              commandOptions: '-out=tfplan'
              environmentServiceNameAzureRM: 'rg-svc'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/tfplan'
              artifact: 'terraform-plan'
              publishLocation: 'pipeline'

  - stage: terraform_apply
    displayName: terraform apply
    dependsOn: terraform_plan
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    jobs:
      - job: terraform_job4
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/'
              backendServiceArm: 'rg-svc'
              backendAzureRmStorageAccountName: 'pipelinestg22092026'
              backendAzureRmContainerName: 'pipelinecontainer22092026'
              backendAzureRmKey: 'pipeline1.tfstate'
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: 'terraform-plan'
              targetPath: '$(System.DefaultWorkingDirectory)'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              
              workingDirectory: '$(System.DefaultWorkingDirectory)/'
              
              commandOptions: 'tfplan'
              environmentServiceNameAzureRM: 'rg-svc'

